### PR TITLE
Move `footer` function to `cnd_footer()` method

### LINKED ISSUE #211: Lifecycle `footer` function captures user's environment - which can result in massive memory explosion
See https://github.com/tidyverse/dplyr/issues/7804

Here's the scenario

- `case_match()` throws a once-per-session lifecycle warning now
- testthat triggers lifecycle warnings unconditionally, not just once per session
- `lifecycle:::deprecate_warn0` **accidentally captures the user's environment** in the warning condition object's `footer` function field
- If you have many tests that trigger the warning AND your user environment is large, then that can result in an OOM crash of R

I actually recently ran into this myself in furrr but had no idea what the problem was. It resolved itself when I got rid of all the deprecation warnings from purrr so I didn't think too much of it.

I wonder if we can change from `footer` as a condition field to a `cnd_footer()` S3 method, and store the minimal amount of stuff in the condition itself that is required to reproduce this footer message from a `cnd_footer()` S3 method instead. That way we don't accidentally capture large function objects in a lifecycle condition.

``` r
library(dplyr)

tibble(
  x = 1:1000
) |> 
  cross_join(
    tibble(
      y = 1:1000
    )
  ) |> 
  mutate(
    v0 = "y"
  ) |> 
  mutate(
    v1 = case_match(v0, "blah" ~ "y")
  )
#> Warning: There was 1 warning in `mutate()`.
#> ℹ In argument: `v1 = case_match(v0, "blah" ~ "y")`.
#> Caused by warning:
#> ! `case_match()` was deprecated in dplyr 1.2.0.
#> ℹ Please use `recode_values()` instead.
#> # A tibble: 1,000,000 × 4
#>        x     y v0    v1   
#>    <int> <int> <chr> <chr>
#>  1     1     1 y     <NA> 
#>  2     1     2 y     <NA> 
#>  3     1     3 y     <NA> 
#>  4     1     4 y     <NA> 
#>  5     1     5 y     <NA> 
#>  6     1     6 y     <NA> 
#>  7     1     7 y     <NA> 
#>  8     1     8 y     <NA> 
#>  9     1     9 y     <NA> 
#> 10     1    10 y     <NA> 
#> # ℹ 999,990 more rows

lobstr::obj_size(
  environment(dplyr:::the$last_warnings[[1]]$cnd$footer)$trace_env[["..."]]
)
#> 24.15 MB

footer_function_captured_in_lifecycle <- dplyr:::the$last_warnings[[1]]$cnd$footer
footer_function_captured_in_lifecycle
#> function (...) 
#> {
#>     footer <- NULL
#>     if (!direct) {
#>         top <- topenv(user_env)
#>         if (is_namespace(top)) {
#>             pkg <- ns_env_name(top)
#>             url <- pkg_url_bug(pkg)
#>             likely_line <- cli::format_inline("The deprecated feature was likely used in the {.pkg {pkg}} package.")
#>             if (is_null(url)) {
#>                 report_line <- "Please report the issue to the authors."
#>             }
#>             else {
#>                 report_line <- cli::format_inline("Please report the issue at {.url {url}}.")
#>             }
#>             footer <- c(footer, i = likely_line, ` ` = report_line)
#>         }
#>     }
#>     if (is_interactive()) {
#>         footer <- c(footer, if (!always) {
#>             cli::col_silver("This warning is displayed once per session.")
#>         }, cli::format_inline(cli::col_silver("Call {.run lifecycle::last_lifecycle_warnings()} to see where this warning was generated.")))
#>     }
#>     footer
#> }
#> <bytecode: 0x10b5087e0>
#> <environment: 0x10b509f20>

# captures everything from the `lifecycle:::deprecate_warn0` frame
names(environment(footer_function_captured_in_lifecycle))
#>  [1] "maybe_push_warning" "wrn"                "trace"             
#>  [4] "footer"             "msg"                "id"                
#>  [7] "always"             "direct"             "call"              
#> [10] "trace_env"          "user_env"

# which includes the `trace_env` argument, which holds user data.
# this `.x` here is `v0` from above!
str(environment(footer_function_captured_in_lifecycle)$trace_env$.x)
#>  chr [1:1000000] "y" "y" "y" "y" "y" "y" "y" "y" "y" "y" "y" "y" "y" "y" ...
```

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #211 

I've shifted us from using an on-the-fly created `footer` function to a `cnd_footer()` S3 method. This forces us to retain the minimal amount of things required to reproduce the `footer` message inside the `cnd` object, which seems to be the `pkg` name of interest and `always`.

We've got quite a few snapshot tests that test the emitted warning messages, so I feel pretty good about this.

```r
library(dplyr)

tibble(
  x = 1:1000
) |> 
  cross_join(
    tibble(
      y = 1:1000
    )
  ) |> 
  mutate(
    v0 = "y"
  ) |> 
  mutate(
    v1 = case_match(v0, "blah" ~ "y")
  )

# BEFORE
lobstr::obj_size(dplyr:::the$last_warnings[[1]]$cnd)
#> 24.20 MB

# AFTER
lobstr::obj_size(dplyr:::the$last_warnings[[1]]$cnd)
#> 22.64 kB
```

### CODE REVIEW

File: R/deprecate.R [hunk 1]
```diff
@@ -247,55 +247,17 @@ deprecate_warn0 <- function(
...
-        }
-
-        footer <- c(
-          footer,
-          "i" = likely_line,
-          " " = report_line
-        )
-      }
-    }
+  trace <- trace_back(bottom = trace_env)
```
Comment (DavisVaughan) [inline R/deprecate.R:250]: I was a bit worried about the fact that `trace` is in the condition object, but it doesn't seem to be _that_ big, so it's probably okay.

File: R/warning.R [hunk 2]
```diff
@@ -38,16 +38,61 @@ last_lifecycle_warnings <- function() {
...
 }
 
-new_deprecated_warning <- function(msg, trace, ..., footer = NULL) {
+new_deprecated_warning <- function(msg, trace, pkg, always) {
   warning_cnd(
     "lifecycle_warning_deprecated",
     message = msg,
     trace = trace,
-    footer = footer,
-    internal = list(...)
```
Comment (DavisVaughan) [inline R/warning.R:47]: We weren't using `internal` for anything

**Review by lionel- — APPROVED** [review]
